service: house-service

provider:
  name: aws
  stage: ${opt:stage, 'local'}
  region: us-east-1
  runtime: nodejs10.x

  iamRoleStatements:
    - Effect: "Allow"
      Action: s3:GetObject
      Resource: arn:aws:s3:::*/*

  environment:
    mongoUri: ${self:custom.mongoUri.${self:provider.stage}}
    defaultRadius: ${self:custom.defaultRadius.${self:provider.stage}}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  
package:
  include:
  exclude:

functions:
  getHouses:
    handler: house/handler.getHouses
    events:
      - http:
          path: houses
          method: get

custom:
  mongoUri:
    local: mongodb://localhost:27017/rent-house
    dev: ${ssm:/renthouse/house/dev/mongoUri}
  defaultRadius:
    local: 2000
    dev: ${ssm:/renthouse/house/dev/defaultRadius}